version: "3"
services:
  mysqldb:
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: notsecure
      MYSQL_DATABASE: trivia_db
  trivia:
    build: .
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: notsecure
      DB_NAME: trivia_db
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"

volumes:
  mysql_volume: {}